# Generated by Django 5.1.2 on 2024-11-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=100, verbose_name='Kargo Adı')),
                ('tracking_number', models.CharField(max_length=50, verbose_name='Takip Numarası')),
                ('tracking_url_template', models.URLField(verbose_name='Takip URL Şablonu')),
            ],
        ),
    ]
