# Generated by Django 5.1.2 on 2024-11-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='tracking_url_template',
        ),
    ]
